default_language_version:
  python: python3

exclude: |
  (?x)^(
    .*thirdparty/.*
  )

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|m|mm|inc|java)$
        args: ["--style=file"]
        types_or: [text]
